### ISSUE TITLE
Add Lawn Block

### ISSUE THREAD

**Issue by Joulanh** [lebonq/Automatic-Path#12]
A way to preserve grasblocks so that they are not affected by pathbuilding, kind of like the new waxed copper mechanic in 1.17, for decorational building purposes.

**Comment by lebonq** [comment]
Ok so I'm thinking about a "Lawn Block" which is craftable and have the same texture as grass block.
1 Dirt + 1 Bone Meal gives you 1 lawn block.
1 GrassBlock + 1 Bone Meal gives you 4 lawn block.
This is what you're thinking about ?

**Comment by Joulanh** [comment]
Yes! Exactly what i was thinking about.
