### ISSUE TITLE
Sheep on paths regrow wool instantly

### ISSUE THREAD

**Issue by NebelNidas** [lebonq/Automatic-Path#29]
This is a bug most likely introduced in #25. Sheep regrow their wool instantly when standing on path blocks, so you can shear them  indefinitely:

https://user-images.githubusercontent.com/48808497/120248316-e9d65780-c276-11eb-910a-0b42fe08bc06.mp4

**Comment by lebonq** [comment]
This is weird I put on top priority !
Are you using 1.16 or 1.17 ?

**Comment by NebelNidas** [comment]
Autopath 1.4.1 on Minecraft 1.16.5

**Comment by lebonq** [comment]
It's weird I cannot reproduce this bug ! I tried in survival and creative.
Do you have another mod installed ?

**Comment by NebelNidas** [comment]
I just generated a new world to check again in a clean environment, and - very weirdly - it works in there! So it seems to be an issue with my old world? Because even with only Fabric API and Autopath installed, it still has the same error (even when spawning brand-new sheep). I can upload the relevant section of my old world and send you the link, if you would like to search for the problem!

**Comment by lebonq** [comment]
Yes if you can I will be pleased to check on your world !

**Comment by NebelNidas** [comment]
Sorry for the late response! Here is the relevant section of my world: [Autopath Issue #29.zip](https://github.com/lebonq/Automatic-Path/files/6668122/Autopath.Issue.29.zip)
It happens with around 40% of the sheep.

Reproducible with:
- Minecraft 1.16.5
- Fabric Loader 0.11.3
- Fabric API 0.35
- Automatic Path 1.4.3

**Comment by NebelNidas** [comment]
Nice to see the other issues getting fixed, but I don't see one for this issue. Have you not been able to reproduce the problem with my attached world section?

**Comment by lebonq** [comment]
I never been able to recreate this weird bug !

**Comment by NebelNidas** [comment]
Even with the world section I sent you? For me, it happened even with a fresh Minecraft install. I'll see if upgrading to 1.17 with the new Autopath versions fixes it, if not, I'm going to tell you
