### ISSUE TITLE
Explain and tag on curseforge page properly

### ISSUE THREAD

**Issue by NighthowlerStudios** [lebonq/Automatic-Path#36]
Your page has the mod tagged for Forge, yet your description claims it requires Fabric.  Please be more clear on the page, and if it really is Fabric only, tag the files properly, please.

**Comment by lebonq** [comment]
There is no file tagged with Forge ? I dont know what you are talking about.

**Comment by NighthowlerStudios** [comment]
Example of correct tagging:

![image](https://user-images.githubusercontent.com/82226641/132044788-e2932051-3272-43b4-a19c-621933990ae2.png)

Example of what happens if you don't add the Forge tag properly
![image](https://user-images.githubusercontent.com/82226641/132044943-d26c91df-3a88-4ea5-bfb7-3b64631b6b32.png)
![image](https://user-images.githubusercontent.com/82226641/132044966-663dc937-9c0e-4f8a-a62d-12ca0aaa1d28.png)

**Comment by NighthowlerStudios** [comment]
You just need to add the fabric tag to 1.2.1 so this stops showing up as usable in my forge pack.  I was very disappointed when I found this false positive :/

**Comment by lebonq** [comment]
Oh yes I see ! I juste add it ! Sorry again for the inconvinient !

**Comment by NighthowlerStudios** [comment]
Thanks!
