### ISSUE TITLE
Crash while wandering around

### ISSUE THREAD

**Issue by TheButterbrotMan** [lebonq/Automatic-Path#41]
https://bytebin.lucko.me/JYpPsiK694

**Comment by lebonq** [comment]
It happen only once ?

**Comment by TheButterbrotMan** [comment]
Two times. But i dont have the another log anymore.

**Comment by lebonq** [comment]
So this is because the enderman as taken a path block in his hands. But this is not normal.
And it crashes because of the color biome

**Comment by Kekor** [comment]
crashed as well for the same reason the endermen picking up the path blocks crashes anyone around. even in normal biomes was able to replicate this after we had the issue on our serve with people in the area of the endermen tested in single player and threw bunch of path blocks around near endermen and crashed when they pick them up

**Comment by TheButterbrotMan** [comment]
You're working on a fix?

**Comment by lebonq** [comment]
> You're working on a fix?

Publish for 1.17.1 and 1.18.2
