### ISSUE TITLE
Files uploaded to Modrinth incorrectly

### ISSUE THREAD

**Issue by RandomGgames** [lebonq/Automatic-Path#46]
Hey! I am making a mod downloader and ran into an issue due to the way you uploaded your mod files to Modrinth. You packed them all together into a single mod version and released all the separate game version files into that mod version. You're supposed to separate each file into it's own version on Modrinth so that mod downloaders are able to distinguish between versions and game versions.

See: https://github.com/orgs/modrinth/discussions/46#discussioncomment-5385653

**Comment by lebonq** [comment]
Thanks for reporting this, I knew something was off when I did this :)
Should be fix by now !
