### ISSUE TITLE
Automatic Path does not get grass block snow texture

### ISSUE THREAD

**Issue by milkev** [lebonq/Automatic-Path#49]
![image](https://github.com/lebonq/Automatic-Path/assets/22010128/f84dc6d9-4690-4973-8772-888fadb76ec8)
![image](https://github.com/lebonq/Automatic-Path/assets/22010128/45fcf0c8-5b08-4095-b04c-276a5d8d98b8)

**Comment by lebonq** [comment]
Currently, I'm using a custom texture for the path block. Should be improved to add a snow texture of the path block.

**Comment by lebonq** [comment]
duplicate of #22
