### ISSUE TITLE
Path in state 1 and 2 should be transform into farmland when a hoe is used

### ISSUE THREAD

**Issue by lebonq** [lebonq/Automatic-Path#8]

**Comment by lebonq** [comment]
I'm gonna add a mixin at the TAIL of the onUseBlock method of HoeItem class.

**Comment by NebelNidas** [comment]
Shouldn't all states be transformable into farmland? Because according to the wiki, both grass blocks and dirt blocks are transformable:
> A player may create a block of farmland by using a hoe on a dirt block, grass block, or grass path.

(https://minecraft.fandom.com/wiki/Farmland#Post-generation)

**Comment by lebonq** [comment]
Yes you'r right, it will be inside the next patch.
